config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'forum', to: 'posts#index'
  get '/', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'products', to: 'products#index'
  get 'orders', to: 'order_items#index'
  devise_for :users
  get 'hello_world', to: 'hello_world#index'
  root to: "pages#home"
  
  get 'politician', to: 'politicians#index'

  get 'cart', to: 'carts#show'

  resource :cart, only: [:show]

  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :update_total
  before_create :update_status

  def calculate_total
    self.order_items.collect { |item| item.product.price * item.quantity }.sum
  end

  private

  def update_status
    if self.status == nil?
      self.status = "In progress"
    end
  end

  def update_total
    self.total_price = calculate_total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

end

app/models/politician.rb
class Politician
  base_url = 'https://www.opensecrets.org/api/?method=candContrib&cid='

  def initialize(politician, year)
    @politician = politician
    @year = year
  end

  def get_contributions
    response = HTTParty.get( 'https://www.opensecrets.org/api/?method=candContrib&cid=' + @politician + '&cycle=' + @year + '&apikey=b4eb17d5d0db345ad67a33a271f763e6')
    data = response.parsed_response

    
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  validates :email, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  helper_method :current_order

  def current_order
    if session[:order_id]
      Order.find(session[:order_id])
    else
      Order.new
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @order_items = current_order.order_items
  end
end

app/controllers/chart_controller.rb
class BookController < ApplicationController
  def index
     @politician = Politician.new.get_books()
   end
end

app/controllers/hello_world_controller.rb
# frozen_string_literal: true

class HelloWorldController < ApplicationController
  layout "hello_world"

  def index
    @hello_world_props = { name: "Stranger" }
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def index
  end

  def create
    @order = current_order
    @item = @order.order_items.new(item_params)
    @order.save
    session[:order_id] = @order.id
    redirect_to products_path
  end

  def destroy
    @order = current_order
    @item = @order.order_items.find(params[:id])
    @item.destroy
    @order.save
    redirect_to cart_path
   end

  private

  def item_params
    params.require(:order_item).permit(:quantity, :product_id, :order_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/controllers/politician_controller.rb
class PoliticianController < ApplicationController
  def index
    politician_object = Politician.new('N00007360', '2018')
    @contribution = politician_object.get_contributions()
  end
end

app/controllers/politicians_controller.rb
class PoliticiansController < ApplicationController
  include Hashie::Extensions::MethodAccess
  def index
    politician_object = Politician.new('N00007360', '2018')
    @contribution = politician_object.get_contributions()
    @cid = @contribution['contributors']
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/carts/show.html.erb
<% if @order_items.any? %>
  <% @order_items.each do |item| %>
    <p><%= item.product.name %> | <%= link_to "Delete", order_item_path(item), :data => {:confirm => "You sure?", :method => "delete"} %></p>
    <p> Unit Price: <%= number_to_currency item.product.price %> | Quantity: <%= item.quantity %> | Total Price: <%= number_to_currency (item.product.price * item.quantity) %></p>
  <% end %>
  <p>Your Total: <%= number_to_currency current_order.total_price %></p>
<% else %>
  <p>Your shopping cart is empty.</p>
<% end %>

app/views/hello_world/index.html.erb
<div class="reveal" id="exampleModal1" data-reveal>
  <%= react_component("HelloWorld", props: @hello_world_props, prerender: false) %>
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<p><button class="button" data-open="exampleModal1">Click me for a modal</button></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Crypto Tracker" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="top-bar">
      <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
          <li class="menu-text">Senate Stacks</li>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          <% if user_signed_in? %>
                <li class="<%= yield(:homeActive) %>"><a href="/">Home</a></li>
                <li class="<%= yield(:homeActive) %>"><a href="/products">Products</a></li>
                <li class="<%= yield(:homeActive) %>"><a href="/orders">Order</a></li>
                <li class="<%= yield(:homeActive) %>"><a href="/forum">Forum</a></li>
                <li class="<%= yield(:aboutActive) %>"><a href="/about">About</a></li>
                <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
                <li><%= link_to "Log In", new_user_session_path %></li>
              <% end %>
        </ul>
      </div>
    </div>
    <% if flash[:notice] %>
      <div class="success callout small" data-closable="slide-out-right">
        <p><%= notice %></p>
        <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert callout small" data-closable="slide-out-right">
        <p><%= alert %></p>
        <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <%= yield %>

  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>


    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  </head>

  <body>
    <div class="top-bar">
      <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
          <li class="menu-text">Site Title</li>
          <li>
            <a href="#">One</a>
            <ul class="menu vertical">
              <li><a href="#">One</a></li>
              <li><a href="#">Two</a></li>
              <li><a href="#">Three</a></li>
            </ul>
          </li>
          <li><a href="#">Two</a></li>
          <li><a href="#">Three</a></li>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          <li><input type="search" placeholder="Search"></li>
          <li><button type="button" class="button">Search</button></li>
        </ul>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/order_items/index.html.erb
<h1 class="title">Order Items</h1>

app/views/pages/about.html.erb
<div class="parent">
  <div class="left-content">

  </div>
  <div class="middle-content">
    <div class="card profile-card-action-icons">
      <div class="card-section">
        <div class="profile-card-header">
          <div class="profile-card-avatar">
            <img class="avatar-image" src="https://avatars1.githubusercontent.com/u/13779974?s=400&u=d606d862df673bcdbc676e111f4f05462d140c36&v=4" alt="Rafael">
          </div>
          <div class="profile-card-author">
            <h5 class="author-title">Rafael Furry</h5>
            <p class="author-description">Full Stack Web Developer</p>
          </div>
        </div>
        <div class="profile-card-about">
          <h5 class="about-title separator-left">About Me</h5>
          <p class="about-content">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet autem eveniet nulla quae ullam sit iure voluptatum, nesciunt voluptas perferendis, minus natus in quaerat?
          </p>
          <div class="row about-skills">
            <div class="small-6 columns">
              <ul class="arrow">
                <li>Coding</li>
              </ul>
            </div>
            <div class="small-6 columns">
              <ul class="arrow">
                <li>Maths</li>
                <li>Music</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="right-content">

  </div>
</div>

app/views/pages/home.html.erb
<h1 class="title">Home</h1>
<div class="center">
  <%= image_tag 'flag.png', size: "300x250", alt: "flag" %>
</div>
<br>
<br>
<hr align="center" width="75%">
<div class="parent">

  <div class="left-content">
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </div>

  <div class="middle-content">
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </div>

  <div class="right-content">
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </div>
</div>

app/views/politicians/index.html.erb
<%= @contribution %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<h1 class="title">Crypto Tracker Forum</h1>
<div class="pad center">
  <table class="center">
    <thead>
      <tr>
        <th width="200">Title</th>
        <th width="500">Post</th>
        <th width="150">User</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= post.body %></td>
          <td><%= post.user.email %></td>
          <td><%= link_to 'Show', post %></td>
          <% if post.user == current_user %>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
            <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New Post', new_post_path, :class => 'button' %>
</div>

app/views/posts/new.html.erb
<h1 class="center">New Post</h1>
<div class="parent center">
  <div class="left-content">
    
  </div>
  <div class="midde-content">
    <%= render 'form', post: @post %>
    <%= link_to 'Back', posts_path%>
  </div>
  <div class="right-content">
    
  </div>
  </div>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="parent">
  <div class="left-content">
    
  </div>
  <div class="middle-content">
    <div class="row">
      <div class="columns large-12">
        <p>
          <strong>Title:</strong>
          <%= @post.title %>
        </p>
      </div>
    </div>

    <div class="row">
      <div class="columns large-12">
        <p>
          <strong>Body:</strong>
          <%= @post.body %>
        </p>
      </div>
    </div>

    <div class="row">
      <div class="columns large-12">
        <%= link_to 'Edit', edit_post_path(@post) %> |
        <%= link_to 'Back', posts_path %>
      </div>
    </div>
  </div>
  <div class="right-content">
    
  </div>
</div>

app/views/products/index.html.erb
<div class="parent">

  <div class="left-content">

  </div>

  <div class="middle-content center">
    <% @products.each do |product| %>
     <p><%= product.name %> | <%= number_to_currency product.price %>
     <%= form_with model: @order_items do |f| %>
       <div class="large-2 columns">
         <div class="field">
           <%= f.hidden_field :product_id, value: product.id %>
           <%= f.number_field :quantity %>
         </div>
         <%= f.submit "Add to cart", :class => 'button'  %>
       </div>
     <% end %></p>
    <% end %>
  </div>

  <div class="right-content">

  </div>

</div>